version: '3.4'

services:
  microservicesquickstart.postsservice.webapi:
    image: microservicesquickstart.postsservice.webapi
    build:
      context: .
      dockerfile: PostsService\WebApi\Dockerfile

  microservicesquickstart.commentsservice.webapi:
    image: microservicesquickstart.commentsservice.webapi
    build:
      context: .
      dockerfile: CommentsService\WebApi\Dockerfile

